# -*- mode: ruby -*-
source 'http://rubygems.org'
gemspec 'ixtlan-guard.gemspec'

if defined? MAVEN
#  plugin('cucumber', '${jruby.plugins.version}').in_phase('integration-test').execute('test')
end

if defined?(JRUBY_VERSION)
  gem 'activerecord-jdbc-adapter'
  gem 'jdbc-sqlite3', :require => false
  gem 'jruby-openssl'
else
  gem 'sqlite3-ruby', :require => 'sqlite3'
end

gem "rspec-rails", '2.0.1'

# vim: syntax=Ruby
