# -*- mode: ruby -*-
source 'http://rubygems.org'

gem 'rails', '3.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3' unless defined?(JRUBY_VERSION)
gem "activerecord-jdbc-adapter" if defined?(JRUBY_VERSION)
gem "jdbc-sqlite3", :require => false if defined?(JRUBY_VERSION)

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  #gem 'nokogiri', '1.4.0.20101020174624'
  #gem 'webrat'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rack-test'
end

gem 'ixtlan-guard'

if defined? MAVEN
  plugin('org.mortbay.jetty.jetty-maven-plugin', '${jetty.version}') do |jetty|
    jetty.with(:stopKey => 'foo', :stopPort => 9999)
    jetty.in_phase('pre-integration-test').execute('run').with(:daemon => true)
    jetty.in_phase('post-integration-test').execute('stop')
  end
  plugin('antrun', '1.3') do |ant|
    ant.in_phase('integration-test').execute('run').with({
            :tasks => <<-XML
<get src="http://localhost:8080/index.html" dest="target/index.html"/>
XML
          })
  end
  plugin('gem', '${jruby.plugins.version}')do |gem|
    gem.in_phase('test').execute("exec").with({
         :script => "ARGV.replace(['spec/requests/users_spec.rb'])
                     load 'target/rubygems/bin/rspec'"
                                             })
  end
end
